spring.application.name=ApiGateway
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://UserService
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**